### ISSUE TITLE
Cannot start radio while Airplay-ing to an Apple TV

### ISSUE THREAD

**Issue by sbrighiu** [fethica/FRadioPlayer#13]
The Player remains stuck in .loading status and needs custom timeout logic.

Reproduce: 
1. Open the app, setup FRadioPlayer, and call play()
2. Wait until you hear the music, and then go into Control Center and Airplay to an Apple TV (not headphones.. it needs to be an Apple TV for this to be reproduce-able)
3. Hear the music playing on the Apple TV
4. Close the app
5. Start the app again and try to play() .. the app will not start now

The route will be selected as AirPlay route and this case was .. to my knowledge not treated.
I've tried to override the port to the .speaker port with no success.

**Comment by fethica** [comment]
Could you check if the same issue happens with the demo app provided in the project? Thanks.

**Comment by sbrighiu** [comment]
Yes the same thing happens on the example app, but there Playing/Pausing/Stopping dont wait for a confirmation that sound is playing, or that it's not (like the first time you start the stream and wait for buffering, or maybe until you have artwork downloaded).

**Comment by fethica** [comment]
I will check this issue as well, thanks!

**Comment by fethica** [comment]
AirPlay route added in [0.1.16](https://github.com/fethica/FRadioPlayer/releases/tag/0.1.16), closing the issue 👍
