### ISSUE TITLE
Airplay to an Apple TV prompts a black screen instead of a now playing notification

### ISSUE THREAD

**Issue by sbrighiu** [fethica/FRadioPlayer#14]
Airplay-ing to an Apple TV device will prompt a black screen with a loader and a progress bar instead of running as a background music app -> TuneIn (which i do believe uses AVPlayer, but i cannot confirm), Soundcloud, Spotify ..

Reproduce: 
1. Open the app, setup FRadioPlayer, and call play()
2. Wait until you hear the music, and then go into Control Center and Airplay to an Apple TV (not headphones.. it needs to be an Apple TV for this to be reproduce-able)
3. Observe the now playing info is not visible anywhere and the screen goes fully black, with only a loader and a progress bar.

The annoying part is the fact that if you dismiss the screen, it does not continue playing the music and will most of the times corrupt the session on that Apple TV.

**Comment by fethica** [comment]
Did you set MPRemoteCommandCenter and MPNowPlayingInfoCenter in your app?

**Comment by sbrighiu** [comment]
Yes, the now playing information is set up and works on the device, but not on the Apple TV.

**Comment by fethica** [comment]
Thanks for reporting the issue, I will do more testing on an actual Apple TV.

**Comment by apeatling** [comment]
Debugging a little more, this only seems to happen when directly using Airplay to an Apple TV. 

Using Airplay 2 you can select multiple devices to airplay to. If I select an Airport Express first, then select the Apple TV as a second Airplay output, the metadata will correctly show in the top right of the Apple TVscreen.

**Comment by apeatling** [comment]
This seems related to the timedMetadata KVO, it always returns nil when directly Airplaying to an Apple TV.

**Comment by fethica** [comment]
@apeatling thanks for the informations!

**Comment by fethica** [comment]
Hey @apeatling , @sbrighiu 

I added a fix to this issue in the latest release [0.1.16](https://github.com/fethica/FRadioPlayer/releases/tag/0.1.16)

**Comment by apeatling** [comment]
Thank you!

**Comment by sbrighiu** [comment]
Awesome! App in review as we speak :)

--------------------------------------
Stefan Brighiu
Software Engineer @ AB4 Systems
Phone: +40 744 581 921
Web: http://ab4.systems

**Comment by fethica** [comment]
Thanks for the feedback, closing the issue 👍
