### ISSUE TITLE
Add support for tvOS

### ISSUE THREAD

**Issue by sbrighiu** [fethica/FRadioPlayer#16]
Can you add tvOS compatibility? It only needs AVAudioSession options to be set to an empty list.

Thanks in advance ;)

**Comment by misteral** [comment]
@fethica
> Can you add tvOS compatibility? It only needs AVAudioSession options to be set to an empty list.

I think after changes with AVAudioSession this will work with MacOS.

**Comment by fethica** [comment]
@sbrighiu I merged @misteral 's changes, could you check if this fixes the issue? Thanks.

**Comment by sbrighiu** [comment]
well i kind of needed it to also support tvOS.. That is not included

**Comment by sbrighiu** [comment]
@fethica i added the changes for tvOS. Should be ok, but please double check? Thanks. And close this once you merge? Have a nice day.
