### ISSUE TITLE
HLS Metadata

### ISSUE THREAD

**Issue by urayoanm** [fethica/FRadioPlayer#23]
Hi:
  There are plans to implement metadata retrieval using HLS streaming? If implemented, any lead how it works?
 Thanks @ Urayoan

**Comment by fethica** [comment]
Hey @urayoanm,

Could you provide an example stream? 

In this project, I'm using KVO to listen to `AVPlayerItem. timedMetadata` changes, it should work with any stream that supports metadata.

**Comment by urayoanm** [comment]
Oh well @fethica, after revieweing the server i was using, right now is not delivering any metadata so i think the project should work properly with a properly configured server :)

Thank you anyways for your response and thank you very much for your contribution with this project and the Swift Radio Pro.

Cheers!
