### ISSUE TITLE
Querying Last.fm or another API

### ISSUE THREAD

**Issue by muzo178** [fethica/FRadioPlayer#25]
A previous version of the SwiftRadio project had the ability to query the Last.fm API in addition to the iTunes API. Since switching the player to the fantastic FRadioPlayer, we can only query the iTunes API.

How could one implement querying the Last.fm API? Or another API for that matter? Say query a url like https://www.exampleapi.fm/meta/**channelname**/live/ for json and get and parse the results?

**Comment by fethica** [comment]
Hey @muzo178 

For now only iTunes API is supported, You can either change the library by updating the [FRadioAPI.swift](https://github.com/fethica/FRadioPlayer/blob/master/Source/FRadioAPI.swift) file or add your own API when there is a metadata change using the delegate method.

But it would be a great feature if we can set our own parser in the framework! Maybe it will be added in a future release 👍

**Comment by gabek** [comment]
Keep in mind, a while back LastFM locked down their images stating nobody was supposed to have them in the first place.

https://getsatisfaction.com/lastfm/topics/api-announcement-dac8oefw5vrxq
