### ISSUE TITLE
Stream starts before Metadata fetching / How to force Metadata fetching

### ISSUE THREAD

**Issue by karolsenami** [fethica/FRadioPlayer#28]
When launching the app (with autoplay), the stream starts to play something like 5 seconds before the track title appears.
Also, without autoplay, is it possible to fetch the current track, before the user starts streaming/calling player.play() ?

**Comment by fethica** [comment]
This is not supported, the play function is separate and doesn't wait for the metadata, I don't know if just loading the stream will trigger the metadata fetching or not.
