### ISSUE TITLE
Need help setup Tack labels updating

### ISSUE THREAD

**Issue by TomAvecLeVdsl** [fethica/FRadioPlayer#34]
Hi everyone , i'm having trouble setting up Track labels updating
i have the function
`func radioPlayer(_ player: FRadioPlayer, metadataDidChange artistName: String?, trackName: String?) { }`

But what to i put in there ? 
i tried to follow exemples but not worked 
Thanks for the help :)

**Comment by fethica** [comment]
Hi @TomAvecLeVdsl 

You need to start by assigning your `class` or `ViewController` as delegate for `FRadioPlayer.shared` instance:

In `viewDidLoad` for example you can add:

```swift
FRadioPlayer.shared.delegate = self
```

Then you add this delegate function to your `controller`:

```swift
unc radioPlayer(_ player: FRadioPlayer, metadataDidChange artistName: String?, trackName: String?) {
    yourArtistNameLabel.text = artistName
    yourTrackNameLabel.text = trackName
 }
```

The `function` will be called automatically each time the stream metadata changes and update you UI accordingly.

**Comment by TomAvecLeVdsl** [comment]
Hi , all good , thanks for help :)
btw is it possible to get back the values when the view get's reloaded ? thanks

**Comment by TomAvecLeVdsl** [comment]
Ok , thanks a lot for the support :) have a great day :)

**Comment by fethica** [comment]
Np! You too :)
