### ISSUE TITLE
Setting User-Agent for AVPlayer.

### ISSUE THREAD

**Issue by csompi** [fethica/FRadioPlayer#37]
Is there a way to set the User-Agent value of the AVPlayer instance in order to show custom data on stream server logs?

![image](https://user-images.githubusercontent.com/5254202/74138521-079b2b80-4bf2-11ea-9e50-c85d48fd7504.png)

**Comment by SwaXTech** [comment]
You did?

**Comment by SwaXTech** [comment]
It works

![Captura de Pantalla 2020-03-22 a la(s) 23 10 01](https://user-images.githubusercontent.com/43499966/77273426-51b40a00-6c92-11ea-8e50-93a29ab01c55.png)
