### ISSUE TITLE
Work for about 30 minutes

### ISSUE THREAD

**Issue by axinggokok** [fethica/FRadioPlayer#38]
Work for about 30 minutes, it will automatically stop, and there is no status callback

**Comment by fethica** [comment]
Hey @axinggokok, can you share more context about this issue and the stream that causes this type of behaviour? Thanks

**Comment by nosenergies** [comment]
I have same problem. 
player switches to "player state loading" and then block on  "ready to play". I don't restart same streaming radio. When I change radio, app can play more 10 minutes, it return to same situation "loading" to "ready to play".  In this time, i must kill app and restart.
