### ISSUE TITLE
Force actualisation of artwork and title

### ISSUE THREAD

**Issue by TomAvecLeVdsl** [fethica/FRadioPlayer#41]
Hi i'm looking in how i can force every X seconds the actualisation of the artwork and title
Thans for giving me some hints how i can do it
Have a great day

**Comment by fethica** [comment]
Hey @TomAvecLeVdsl 

I think you will have to make the change in the FRadioPlayer.swift file, and add a `Timer` to handle the refresh, for example 10 sec:

```swift
let artworkRefreshTimer = Timer.scheduledTimer(timeInterval: TimeInterval(10), target: self, selector: #selector(refreshArtwork), userInfo: nil, repeats: true)
```

```swift
@objc func refreshArtwork() {
    timedMetadataDidChange(rawValue: playerItem?.timedMetadata?.first?.value as? String)
}
```

**Comment by TomAvecLeVdsl** [comment]
Ok, thanks for the info, have a great day :)
