### ISSUE TITLE
How to play in background?

### ISSUE THREAD

**Issue by Datastore24Kirill** [fethica/FRadioPlayer#44]
How can I make sure that music continues to play when minimizing the application.

**Comment by fethica** [comment]
Hey @Datastore24Kirill 

Make sure that the background mode is checked for Audio, Airplay and PiP in the capabilities section of your app:

![Screen Shot 2019-12-28 at 8 55 12 PM](https://user-images.githubusercontent.com/3511384/71551396-7448c680-29b4-11ea-8479-32fb78dff9c8.png)
