### ISSUE TITLE
Radio doesn't resume after network interruption - Wifi (working for cellular)

### ISSUE THREAD

**Issue by HimaKrishna** [fethica/FRadioPlayer#47]
Hello Fethica,

I have been using the FRadio library in my radio app and encountered an issue. When there is a network interruption and the network type is Wifi -  the radio pauses and when the connection is back, the Radio wouldn't resume though the player state is 'Ready to play'. This is working fine with cellular data but not working with Wifi. 
Please note that I have tested this on my iPhone 8 Plus device, however the same scenario is working fine in the simulator (radio resumes). 
We have a release planned early next week and this is the show stopper. So, kindly get back to me ASAP.

Thank you.

Regards,
Hima

**Comment by fethica** [comment]
Hey @HimaKrishna 

A couple of users have already mentioned the same issue, I'm looking into that!

**Comment by HimaKrishna** [comment]
> Hey @HimaKrishna
> 
> A couple of users have already mentioned the same issue, I'm looking into that!
Thanks Fethica, I would like to provide more info on this. It seems like the issue is when the User turn OFF the wifi and turned it ON from the Control centre on iPhone, the radio player did not resume. But when the User turn the Wifi OFF the Wifi from the Settings and turn it back, the player is working fine (Resumes the stream).
I believe there is an issue in the reachability related to the command centre. Hope this helps you in your investigation.

**Comment by fethica** [comment]
hum interesting!

Thanks for the details @HimaKrishna that will really help 👍

**Comment by sukov** [comment]
My recommendation for you is to use Alamofire's [`NetworkReachabilityManager`](https://github.com/Alamofire/Alamofire/blob/master/Source/NetworkReachabilityManager.swift).
