### ISSUE TITLE
Local File Skimming

### ISSUE THREAD

**Issue by sp71** [fethica/FRadioPlayer#48]
I tried this out with radio urls and was a great solution. Since it also works with local files, is it possible to introduce a skimming feature? For example, it plays a local file and if the user decides, they can fast forward the song to continue playing at another point? Would be great to also have the progress of the file. Meaning the user is 60% along the song so developers can create a UI element to inform users how much of the song is left and how much has been played

**Comment by fethica** [comment]
Hey @sp71 !

Sorry for the late reply, check the `FS` branch it has this feature, I will upgrade the master branch to support the audio files as well.
