### ISSUE TITLE
Difference between .loadingFinished and .readyToPlay

### ISSUE THREAD

**Issue by LinusU** [fethica/FRadioPlayer#5]
I'm having some problems figuring out the difference between `.loadingFinished` and `.readyToPlay`. From what I've observed, it seems like as soon as the stream starts playing the status first gets changed to `.readyToPlay`, and then directly after changes to `.loadingFinished` and stays there.

In the app I'm currently working on I basically only have three states: `stopped`, `loading`, `playing`. I'm currently using the following logic to determine what state I'm in, and it seems to be working fine, but I'm not sure if it's "correct" and will always work...

```swift
class FooBar {
    // ...

    internal func refreshState() {
        if player.playbackState == .stopped {
            self.state = .stopped
        }

        if player.state == .loading {
            self.state = .loading
        }

        if player.state == .loadingFinished && player.playbackState == .playing {
            self.state = .playing
        }
    }

    func radioPlayer(_ player: FRadioPlayer, playerStateDidChange state: FRadioPlayerState) {
        refreshState()
    }

    func radioPlayer(_ player: FRadioPlayer, playbackStateDidChange state: FRadioPlaybackState) {
        refreshState()
    }
}
```

**Comment by fethica** [comment]
There is 2 types of player state: `player.state` and `player.playbackState`, the first one is a simple  representation of `AVPlayerItem` and `AVPlayer` status:

`.loadingFinished` == `AVPlayerItem.isPlaybackLikelyToKeepUp`
`.loading` == `!AVPlayerItem.isPlaybackLikelyToKeepUp` or `AVPlayerItem.isPlaybackBufferEmpty`
`.readyToPlay` == AVPlayerStatus.readyToPlay`

If you want to know more details about the difference between `isPlaybackLikelyToKeepUp` and `readyToPlay ` check out [this](https://stackoverflow.com/a/35233750)

For your `refreshState()` it depends on how your player will be implemented, if you are going to ignore the pause state? I think that might work! But you need to do more testing ...

**Comment by analogcode** [comment]
Thanks for the great answer, @fethica! 👍🏼
