### ISSUE TITLE
Continue play from current stream, not pause

### ISSUE THREAD

**Issue by ucelme** [fethica/FRadioPlayer#51]
Hello. How I can continue play audio from current stream, and not from paused location when I use player.togglePlaying()?

**Comment by fethica** [comment]
Hello!

You can add an extension to the FRadioPlayer that toggles playing using stop instead of pause:

```swift
extension FRadioPlayer {
    open func toggleStopPlaying() {
        isPlaying ? stop() : play()
    }
}
```
