### ISSUE TITLE
Car Play crash 

### ISSUE THREAD

**Issue by himabinduach** [fethica/FRadioPlayer#69]
Hello Fethica,

We have a music audio app which we built car play using your tutorial - https://blog.fethica.com/add-carplay-support-to-swiftradio/ . The app is working fine on simulator, but when tested on a real car, it crashed right after tapping the app icon on car dashboard. We have followed the same steps mentioned in the post above by extending the App Delegate with 'MPPlayableContentDelegate'. Do you have any suggestions why the app may crash in real time? Below is the thread that is causing the failure. Also, we are using Fradio player for our music app.

Please do the needful. Thank you

[crashlog.pdf](https://github.com/fethica/FRadioPlayer/files/6124998/crashlog.pdf)

**Comment by urayoanm** [comment]
Hello. You need the CarPlay entitlement from Apple. If is not set the app will crash. 

https://developer.apple.com/documentation/carplay/requesting_the_carplay_entitlements?language=objc
