### ISSUE TITLE
Does it support rtmp?

### ISSUE THREAD

**Issue by quangkz** [fethica/FRadioPlayer#72]
I want to play some rtmp link

**Comment by fethica** [comment]
Hi @quangkz , 

The library is based on [`AVPlayer`](https://developer.apple.com/documentation/avfoundation/avplayer) so it will only play the formats [supported by Apple](https://stackoverflow.com/questions/21879981/avfoundation-avplayer-supported-formats-no-vob-or-mpg-containers).

To play other formats, you'll need to replace the `AVPlayer` instance in the library with a custom player that supports these formats.
