### ISSUE TITLE
Audio not being played on iPhone 6 on real device

### ISSUE THREAD

**Issue by inamlango** [fethica/FRadioPlayer#9]
Audio is playing back on every device and simulator except iPhone 6 and 6+ both have iOS 11.2

Always fails with the following error when trying to playback from a URL
Credstore - performquery - error copying matching creds

**Comment by fethica** [comment]
Hi @inamlango , I updated the project to Swift 4.2 and Xcode 10, could you check if the problem still exists with this new version? Thanks.
